/*
 * Generated by ISE 25.02.9.8732 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F302_6305();
extern void F304_6467();
extern void F302_6309();
extern void F305_6471();
extern void F307_6635();
extern void F305_6476();
extern void F432_4031();
extern void F352_6151();
extern void F148_1677();
extern EIF_REFERENCE F148_1664();
extern EIF_BOOLEAN F148_1676();
extern EIF_BOOLEAN F148_1684();
extern void F148_1686();
extern void F148_1687();
extern void F148_1688();
extern void F86_1332();
extern EIF_TYPED_VALUE F86_1333();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F302_6305;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F302_6309;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F305_6471;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F305_6476;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F432_4031;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F304_6467;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F307_6635;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F352_6151;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F148_1677;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F148_1676;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F148_1664;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F148_1684;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F148_1686;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F148_1687;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F148_1688;

	egc_str_dtype = 303;

	egc_immstr8_dtype = 302;

	egc_str32_dtype = 306;

	egc_immstr32_dtype = 305;
	egc_arr_dtype = 431;
	egc_tup_dtype = 255;
	egc_disp_rout_id = 2326;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x021A;
	egc_sp_wchar = 0x02B2;
	egc_sp_bool = 0x03C8;
	egc_sp_uint8 = 0x014B;
	egc_sp_uint16 = 0x03A5;
	egc_sp_uint32 = 0x026B;
	egc_sp_uint64 = 0x01F5;
	egc_sp_int8 = 0x035D;
	egc_sp_int16 = 0x0339;
	egc_sp_int32 = 0x01C7;
	egc_sp_int64 = 0x0381;
	egc_sp_real32 = 0x02F0;
	egc_sp_real64 = 0x0314;
	egc_sp_pointer = 0x028F;
	egc_sp_ref = 0x01B2;

	egc_uint8_dtype = 293;
	egc_uint16_dtype = 275;
	egc_uint32_dtype = 272;
	egc_uint64_dtype = 269;
	egc_int8_dtype = 266;
	egc_int16_dtype = 263;
	egc_int32_dtype = 260;
	egc_int64_dtype = 257;
	egc_bool_dtype = 290;
	egc_real32_dtype = 278;
	egc_char_dtype = 287;
	egc_wchar_dtype = 284;
	egc_real64_dtype = 281;
	egc_point_dtype = 296;

	egc_exception_dtype = 104;
	egc_except_emnger_dtype = 147;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "simple_encryption";
	egc_system_location = "D:\\prod\\simple_encryption\\EIFGENs\\simple_encryption_tests\\W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1765236402;
	egc_has_old_special_semantic = 0;
	scount = 1034;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "ENCRYPTION_TEST_APP.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 1009;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 2897;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 5408;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 85;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F86_1332;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F86_1333;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 56; /* ENCRYPTION_TEST_APP */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 207; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 326; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
